parameters:
    memcached_host: 127.0.0.1
    memcached_port: 11211
    memcached_prefix: session_
    memcached_expire: 14400

services:
#    gescom.example:
#        class: GescomBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    gescom.navigator.factory:
        class: GescomBundle\Tools\NavigatorFactory
        arguments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"

    gescom.navigator:
        class: GescomBundle\Tools\Navigator
        factory: "gescom.navigator.factory:get"

    session.handler.memcached:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [ "@session.memcached", { prefix: '%memcached_prefix%', expiretime: '%memcached_expire%' } ]

    session.memcached:
        class: Memcached
        calls:
            - [addServer, [%memcached_host%, %memcached_port%]]