services:
#    gescom.example:
#        class: GescomBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    gescom.navigator.factory:
        class: GescomBundle\Tools\NavigatorFactory
        arguments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
            - "@gescom.filter.transform"

    gescom.navigator:
        class: GescomBundle\Tools\Navigator
        factory: "gescom.navigator.factory:get"

    gescom.filter.transform:
        class: GescomBundle\Tools\FilterTransform
