# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
#        in_memory:
#            memory:
#                users:
#                    admin:
#                        password: $2y$12$OOP7TG4z7cfWfzwbzXDATupLzcIKNICUFClMfc8zSONvy350WJ5WO
#                        roles: 'ROLE_ADMIN'
#                    laurent:
#                        password: $2y$12$OOP7TG4z7cfWfzwbzXDATupLzcIKNICUFClMfc8zSONvy350WJ5WO
#                        roles: 'ROLE_READER'
        dbal:
            entity:
                class: GescomBundle:User
                property: username
    encoders:
        GescomBundle\Entity\User:
            algorithm: bcrypt
    firewalls:
        dev:
            anonymous: ~
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /

            anonymous: ~
            provider: dbal
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [IS_AUTHENTICATED_REMEMBERED] }