# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$OOP7TG4z7cfWfzwbzXDATupLzcIKNICUFClMfc8zSONvy350WJ5WO
                        roles: 'ROLE_ADMIN'
                    laurent:
                        password: $2y$12$OOP7TG4z7cfWfzwbzXDATupLzcIKNICUFClMfc8zSONvy350WJ5WO
                        roles: 'ROLE_READER'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }