<?php

namespace GescomBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductById($id)
    {
        $query = $this->createQueryBuilder('p')
                      ->select("p, ps, s")
                      ->join("p.productSupplier", "ps")
                      ->join('ps.supplier', "s")
                      ->where("p.id = $id")
                      ->getQuery();
        return $query->getResult()[0];
    }
}
