<?php

namespace GescomBundle\Repository;

use Doctrine\ORM\EntityRepository;
use GescomBundle\Tools\Navigator;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends EntityRepository
{
    const MAX_RESULT = 10;

    public function getRowsByPage($page, $filter)
    {
        $alias = "s";
        $query = $this->createQueryBuilder($alias)
            ->select($alias)
            ->setFirstResult(($page - 1) * self::MAX_RESULT)
            ->setMaxResults(self::MAX_RESULT);
        if (!is_null($filter)) {
            foreach ($filter as $field => $value) {
                if ($value !== "") {
                    if (strpos($field, "_") !== 0) {
                        $search = "$alias.$field like '%$value%'";
                        $query->andWhere($search);
                    }
                }
            }
        }
        return $query->getQuery();
    }

    public function getCategoriesBySupplier($supplierId)
    {
        $qb = $this->createQueryBuilder("s")
            ->select(["s.name as supplier", "c.name as category"])
            ->join("s.productSupplier", "ps")
            ->join("ps.product", "p")
            ->join("p.category", "c")
            ->where("s.id = $supplierId")
            ->groupBy("c.id")
            ->getQuery();
        return $qb->getResult();
    }
}
